### PR TITLE
Use editor widget

### LINKED ISSUE #6: Using configured edit widget
This plugin is very helpful to quickly change attributes.
It would be very nice to be able to use the configured edit widget instead of just plain text. This would allow to use comboboxes, date widgets and much more.

Would this be something that is desirable and that has the potential to be integrated here?

### PR DESCRIPTION
**Pull request by m-kuhn**
As requested, this revives #7 without the change of the .py to .ui file.

With this change it's possible to make use of value lists, etc.

Peek 2020-11-14 11-56

Fixes #6

### CODE REVIEW

**Comment by dayjournal** [comment]
@m-kuhn 
Hi,
Fixed again based on the pull request. 
Please confirm.

[feature/ui-change](https://github.com/dayjournal/AttributeAssignment/tree/feature/ui-change)

**Comment by m-kuhn** [comment]
@dayjournal 
sorry, what exactly do I need to confirm?

**Comment by dayjournal** [comment]
@m-kuhn 
Hi,
UI changes and avoiding errors when clicking on the canvas when the field is not selected.

**Comment by m-kuhn** [comment]
looks good to me, thank !

**Pull request merged**
